
use master
go
--drop database SOWCONNECT_DB
create database SOWCONNECT_DB
go
use SOWCONNECT_DB
go

CREATE TABLE Banco(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	NomeInstituicao VARCHAR(MAX) NOT NULL,
	CodigoInstituicao VARCHAR(3) NOT NULL
)

CREATE TABLE Cliente(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	IdBanco INT FOREIGN KEY REFERENCES Banco(Id) NOT NULL,
	TipoCliente INT NOT NULL,
	Nome VARCHAR(MAX) NOT NULL
)

CREATE TABLE ContaBancaria(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	IdBanco INT FOREIGN KEY REFERENCES Banco(Id) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(Id) NOT NULL,
	Agencia VARCHAR(MAX) NOT NULL,
	ContaCorrente VARCHAR(MAX) NOT NULL,
	Saldo DECIMAL(18,2) NOT NULL,
)

CREATE TABLE Movimentacao(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	TipoMovimentacao INT NOT NULL,
	IdContaOrigem INT FOREIGN KEY REFERENCES ContaBancaria(Id) NOT NULL,
	IdContaDestino INT FOREIGN KEY REFERENCES ContaBancaria(Id) NOT NULL,
	Valor DECIMAL(18,2) NOT NULL,
	DataMovimentacao DATETIME NOT NULL
)
